### ISSUE TITLE
Are the heading/intro text fields duplicates of one another?

### ISSUE THREAD

**Issue by megawatts64** [n64blog/n64blog.github.io#10]
Currently the feature article title and bold intro text are identical. I can't tell if it's because the same text has been put in two separate fields or if they are linked in some way?

If it is the latter, then is there a way to unlink it? The title will almost always need to be shorter than the intro text. The title for this article is "The 20th anniversary of the Nintendo 64", although I now would like to rename it to "The Nintendo 64 is now 20 years old".

**Comment by ash-lift** [comment]
The reason it is repeated is lazy copy and pasting. The post heading is pulled in from the YAML data at the top of the markdown file. I'll change the title shortly.
