### ISSUE TITLE
Write site description

### ISSUE THREAD

**Issue by ash-lift** [n64blog/n64blog.github.io#12]
Write a brief site description for the config file

**Comment by megawatts64** [comment]
Just to clarify, do you mean the meta description that would typically appear in Google search engine results?

**Comment by ash-lift** [comment]
Yep

**Comment by megawatts64** [comment]
Blog meta title: Nintendo 64 games, news, videos | N64 Blog

Meta description: Indulge your nostalgia for the Nintendo 64 by exploring the console's games, hardware and peripherals. Includes latest N64 news.

Meta keywords: "n64 blog", "nintendo 64", "n64", "n64 games", "n64 website"

**Comment by megawatts64** [comment]
New site title is not showing on site or in Google SERPs. Meta description appears in page code but not Google; could be that Google has not re-indexed the website since last time.

Also, "| N64 blog" currently appears at the end of all pages; this should be "| N64 Blog".
