### ISSUE TITLE
Two descriptions needed urgently

### ISSUE THREAD

**Issue by guypursey** [n64blog/n64blog.github.io#33]
As far as I can see there are currently no descriptions for _Goldeneye_ or _Majora's Mask_ even though these pages have been live for a while. If descriptions are added to the spreadsheet, I'll re-run the script to update the pages.

**Comment by megawatts64** [comment]
I have now written the descriptions for these games and added them to the spreadsheet. If you could please run the script and then close this thread to confirm, I would be very grateful!

I've also tweaked a few other entries after noticing a number of typos in the descriptions for them (d'oh!).

**Comment by guypursey** [comment]
Cool. I'll update the two files explicitly mentioned in this issue to close it off, including renaming boxart to reflect the changes in the spreadsheet. I'll then update the other gamepages through a business-as-usual script run.

**Comment by guypursey** [comment]
@megawatts64 Although this issue is now closed I thought I'd add that the corrections mentioned above have now been imported and are on the live site.
