### ISSUE TITLE
Redundant labelling on gamepages

### ISSUE THREAD

**Issue by guypursey** [n64blog/n64blog.github.io#35]
Some labels, like "Related posts" and Japanese release date labels, need hiding where there is no content to be found. Suggest some conditionals in the template files which would wrap these labels and any associated tags and only show them where there's a relevant value.

Here's an image of what I mean:

![n64-blog-gamepages-redundant-labelling](https://cloud.githubusercontent.com/assets/1826451/21289429/c094a04a-c495-11e6-971b-c53d50351649.png)

**Comment by ash-lift** [comment]
@guypursey I've taken a look and can't figure out a conditional that will fix this without breaking something else. Any ideas?

**Comment by guypursey** [comment]
@ash-lift: I wasn't sure what you meant but guessed that it might be the "Related posts" label as the release date labels all seemed to be set up with conditionals correctly. Don't know what you tried but I ended up having to rewrite the way the tags and posts arrays were handled slightly. Happy to provide more detail if you want it!

**Comment by ash-lift** [comment]
Thanks for looking at this, yes I already sorted the release date labels, it was the related posts that were causing issues as the loop never returned empty but you've sorted that out :)

**Comment by ash-lift** [comment]
Fixed in #44
