### ISSUE TITLE
Missing/incorrect file names for box art images

### ISSUE THREAD

**Issue by megawatts64** [n64blog/n64blog.github.io#40]
The attached list shows 72 entries of images that have either not been uploaded to the assets folder or do not have the assigned filename as specified in the game pages properties spreadsheet.

Can these please be corrected?

[Missing images - N64 Blog - 18 Dec 2016.xlsx](https://github.com/n64blog/n64blog.github.io/files/659674/Missing.images.-.N64.Blog.-.18.Dec.2016.xlsx)

**Comment by ash-lift** [comment]
Most of them sorted as part of #46, still need the following:

- [ ] bakuretsu-muteki-bangaioh.jpg
- [ ] densha-de-go-64.jpg
- [ ] f1-racing-championship.jpg
- [ ] michael-owen-wls-2000.jpg
- [ ] transformers-beast-wars-transmetals.jpg
