### ISSUE TITLE
Create sitemap

### ISSUE THREAD

**Issue by megawatts64** [n64blog/n64blog.github.io#45]
Create sitemap that is linked to in the site footer. I will then submit this to Google Search Console.

Please let me know when this has been done so I can submit.

**Comment by ash-lift** [comment]
Sitemap created in #46. Content can be changed as it is just an markdown file

**Comment by ash-lift** [comment]
Human sitemap created, looking into this [plugin](https://github.com/jekyll/jekyll-sitemap) in for the xml version
