### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by ash-lift** [n64blog/n64blog.github.io#49]
We need a 404 page. This could be a really fun page, any ideas what we could do? e.g. does the N64 or any games have an error screen we could replicate?

**Comment by megawatts64** [comment]
Excellent idea! I'll have a look at error screens and come back to this thread soon. We could base it on the absolutely bonkers game over screen from Goemon perhaps!

**Comment by ash-lift** [comment]
Oooo I like that idea

**Comment by megawatts64** [comment]
Been thinking about this. I was wondering if we could do a mickey-take on something like the attached image? Same thing but replace the N64 and controller with different assets?

Might require you to boot up Mario Tennis 64 in an emulator so you can capture the image at a high enough resolution to be usable.

![mario-tennis-64-no-controller-screen](https://cloud.githubusercontent.com/assets/23094937/23331556/2d5fdf04-fb60-11e6-9490-d0d7c6571a71.jpg)
