### ISSUE TITLE
Game review pages

### ISSUE THREAD

**Issue by megawatts64** [n64blog/n64blog.github.io#57]
As discussed, we want to create a new subsection of the blog for game reviews. The initial requirements and tasks are as follows (in order):

- [x] 1. @megawatts64 to devise scoring system, write standardised disclaimer and reviews policy/overview page content, and provide details to @ash-lift  ahead of template creation.
- [ ] 2. @ash-lift to produce game review post template that includes a selectable/editable scoring field and pulls through game page information sidebar (must not be duplicated otherwise inconsistencies can occur - EDITED by @megawatts64 25/02/2017)
- [x] 3. @ash-lift to create reviews policy/overview page using content provided by @megawatts64 - this will need to be linked to in the standardised disclaimer.
- [x] 4. @ash-lift to create a reviews category page that is accessible from the sidebar navigation. In terms of functionality this would resemble the standard feed but be configured to show only reviews. 
- [ ] 5. @ash-lift to modify the existing game page template to display a link to the respective review for a game page. This should ideally only be visible when a game review for that page already exists.
- [x] 6. @megawatts64 to write first game review to populate template
- [ ] 7. @ash-lift to push project live

Given the crossover between content and design for this, I suggest that we assign the issue back and forth between assigned tasks (rather than being assigned simultaneously) so it is clear whose action is required at that point.

Go-live date: Sunday 2 April 2017
Progress review: 19 March 2017

Please confirm you are happy with the details in comments and then we can assign issue to me to commence work on first task. Otherwise, let me know if anything needs changing/correcting.

**Comment by megawatts64** [comment]
I have written the copy for the "Our game review scoring system" page as well as the disclaimer text that should appear at the bottom of each review. I've also given some context in the latter on how it should ideally display the score and additional "summary information".

I've shared these with you on Google Drive, but the links are below for your convenience:

- [Our game review scoring system](https://docs.google.com/document/d/10s2rkG2CgBvJZvDToSwj_jLN5yyRql8aFl3VfpBzGME/edit)
- [Score and review disclaimer text](https://docs.google.com/document/d/1Y5-Z4cHX2nvPv0-g4dQR-y4lmrlBELp2mhpkESvY_EI/edit)

If you are not able to display something as I've suggested or feel there is a better way to do it then please post a comment on here for discussion first. This is just so that I know what to expect and reduces the risk of us having to spend time changing stuff later on.

Cheers!

**Comment by megawatts64** [comment]
Progress review:

I've completed task 1, but still need to complete task 6 (write a review). I am confident I can get this done before 2 April. I will write a review for Banjo-Kazooie, so no time required for playing/research.

**Comment by ash-lift** [comment]
__Progress review:__

Review template mostly done, just need to implement pro/con list. New fields added are 
- 'layout: review' - Makes the page use the review template
- 'score: x' - takes a number 1-100
- 'the-good:' - takes an array, e.g ["Testing", "Stuff thats good", "Yep"]
- 'the-bad:' - takes an array, e.g ["the bad", "Stuff thats crap", "nope", "nope", "nope"]

Reviews category and policy pages are complete.

I'll look to create a PR next week when the pro/con list stuff is ready

**Comment by ash-lift** [comment]
Updated comment above with extra details for the pro/con list

**Comment by megawatts64** [comment]
Banjo-Kazooie review has now been uploaded to the PR in the posts folder. Images have been uploaded to master already.
