### ISSUE TITLE
Widen post text area

### ISSUE THREAD

**Issue by megawatts64** [n64blog/n64blog.github.io#8]
Would it be possible to widen the maximum width of the header and body copy in posts?

While not having text run across the full page width results in a better user experience, the text sections are currently quite narrow, meaning that headers will need to be very short to prevent running across multiple lines. Longer articles, such as the 20th Anniversary piece, require considerable scrolling.

Naturally I am aware that this will be dependent on the device being used (for example, it looks fine on my Samsung Galaxy III Mini). On iPad (3rd Gen - see image attached) there's a fair bit of space in the left sidebar that could potentially be reduced to accommodate the text. I can't include a desktop image but this request primarily relates to how it shows on a much larger screen.

![image](https://cloud.githubusercontent.com/assets/23094937/19810052/c9809a5e-9d23-11e6-8793-6c55649fdb8a.png)

**Comment by ash-lift** [comment]
Line length at wider screens feels comfortable to me, the page titles are more problematic so will widen a little bit but only by 5%.
