### ISSUE TITLE
Page titles are all identical

### ISSUE THREAD

**Issue by megawatts64** [n64blog/n64blog.github.io#9]
Not sure if this is an error or the info simply hasn't been inserted yet.

Currently all pages share the page title "N64 Blog" despite having different H1s in the page content. It would be good if page titles could be different to H1s, just in case an H1 is too long and we need to get creative with character limits for search engines. Having the name of the blog automatically appear the end of each page title would also be ideal.

Update: this is only for posts, not game pages.

**Comment by ash-lift** [comment]
Right now the title is set-up like this:

`{% if page.title %}{{ page.title | escape }}{% else %}{{ site.title | escape }}{% endif %}`

So if a page has a title defined in the YAML front matter, that will be in the title. If no title has been defined it falls back to the blog title. I can easily change is if you want, how about:
- a custom title as defined in the YAML front matter (we will call it `head-title`), followed by 'N64 Blog'
- if no `head-title` is defined it will use pages title followed by 'N64 Blog'

Does this sound ok?

**Comment by megawatts64** [comment]
This sounds good to me! Make it so!
